"""Compatibility export surface for MCP tool implementations."""

from __future__ import annotations

from features.climate.mcp import (
    tool_get_climate_location,
    tool_list_climate_datasets,
    tool_search_climate_locations,
)
from features.mcp.tools_assets import (
    get_asset_service,
    tool_bulk_attach,
    tool_bulk_detach,
    tool_get_asset_url,
    tool_get_job,
    tool_list_assets,
    tool_resolve_asset_urls,
    tool_start_bulk_download,
)
from features.mcp.tools_custom_fields import (
    tool_add_custom_field,
    tool_change_custom_field_type,
    tool_delete_custom_field,
    tool_duplicate_custom_field,
    tool_edit_custom_field_options,
    tool_rename_custom_field,
    tool_set_custom_field_description,
    tool_set_custom_field_formula,
)
from features.mcp.tools_documents import (
    tool_discard_draft,
    tool_get_document,
    tool_get_table,
    tool_replace_table,
    tool_save_draft,
)
from features.mcp.tools_envelope import (
    tool_apply_envelope_command,
    tool_list_envelope_assemblies,
    tool_list_project_materials,
    tool_query_unfinished_envelope_work,
    tool_report_material_catalog_drift,
    tool_report_missing_envelope_evidence,
)
from features.mcp.tools_model_viewer import (
    tool_create_hbjson_file,
    tool_delete_hbjson_file,
    tool_get_hbjson_file_download_url,
    tool_get_hbjson_model_data,
    tool_list_hbjson_faces,
    tool_list_hbjson_files,
    tool_list_hbjson_hot_water_systems,
    tool_list_hbjson_shading_elements,
    tool_list_hbjson_spaces,
    tool_list_hbjson_ventilation_systems,
    tool_rename_hbjson_file,
)
from features.mcp.tools_projects import (
    tool_delete_project,
    tool_get_project,
    tool_hard_delete_project,
    tool_list_projects,
    tool_list_status_items,
    tool_list_versions,
    tool_restore_project,
)
from features.project_climate_source.mcp import tool_list_project_climate_sources
from features.project_location.mcp import tool_get_project_location, tool_get_project_sun_path

__all__ = [
    "tool_add_custom_field",
    "get_asset_service",
    "tool_apply_envelope_command",
    "tool_bulk_attach",
    "tool_bulk_detach",
    "tool_change_custom_field_type",
    "tool_create_hbjson_file",
    "tool_delete_custom_field",
    "tool_delete_hbjson_file",
    "tool_delete_project",
    "tool_discard_draft",
    "tool_duplicate_custom_field",
    "tool_edit_custom_field_options",
    "tool_get_asset_url",
    "tool_get_climate_location",
    "tool_get_document",
    "tool_get_hbjson_file_download_url",
    "tool_get_hbjson_model_data",
    "tool_get_job",
    "tool_get_project",
    "tool_get_project_location",
    "tool_get_project_sun_path",
    "tool_get_table",
    "tool_hard_delete_project",
    "tool_list_assets",
    "tool_list_climate_datasets",
    "tool_list_envelope_assemblies",
    "tool_list_hbjson_faces",
    "tool_list_hbjson_files",
    "tool_list_hbjson_hot_water_systems",
    "tool_list_hbjson_shading_elements",
    "tool_list_hbjson_spaces",
    "tool_list_hbjson_ventilation_systems",
    "tool_list_project_climate_sources",
    "tool_list_project_materials",
    "tool_list_projects",
    "tool_list_status_items",
    "tool_list_versions",
    "tool_query_unfinished_envelope_work",
    "tool_rename_custom_field",
    "tool_rename_hbjson_file",
    "tool_replace_table",
    "tool_report_material_catalog_drift",
    "tool_report_missing_envelope_evidence",
    "tool_resolve_asset_urls",
    "tool_restore_project",
    "tool_save_draft",
    "tool_search_climate_locations",
    "tool_set_custom_field_description",
    "tool_set_custom_field_formula",
    "tool_start_bulk_download",
]
