"""Add Glazing Attributes

Revision ID: 02c1612310e1
Revises: 6b54b6a4efc8
Create Date: 2025-08-17 16:15:19.614746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c1612310e1'
down_revision: Union[str, None] = '6b54b6a4efc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aperture_glazing_types', sa.Column('manufacturer', sa.String(length=255), nullable=True))
    op.add_column('aperture_glazing_types', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('aperture_glazing_types', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('aperture_glazing_types', sa.Column('datasheet_url', sa.String(), nullable=True))
    op.add_column('aperture_glazing_types', sa.Column('link', sa.String(), nullable=True))
    op.add_column('aperture_glazing_types', sa.Column('comments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aperture_glazing_types', 'comments')
    op.drop_column('aperture_glazing_types', 'link')
    op.drop_column('aperture_glazing_types', 'datasheet_url')
    op.drop_column('aperture_glazing_types', 'source')
    op.drop_column('aperture_glazing_types', 'brand')
    op.drop_column('aperture_glazing_types', 'manufacturer')
    # ### end Alembic commands ###
