"""Update Frame Types Attributes

Revision ID: 515cec25d286
Revises: fd4af8236c7d
Create Date: 2025-08-17 14:43:13.613878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515cec25d286'
down_revision: Union[str, None] = 'fd4af8236c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add with server_default so existing rows get populated, then drop default if not desired
    op.add_column(
        'aperture_frame_types',
        sa.Column('psi_g_w_mk', sa.Float(), nullable=False, server_default='0.04')
    )
    # Optional: remove the server default after backfilling so future inserts rely on app logic
    op.alter_column('aperture_frame_types', 'psi_g_w_mk', server_default=None)
    op.add_column('aperture_frame_types', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('aperture_frame_types', sa.Column('use', sa.String(length=255), nullable=True))
    op.add_column('aperture_frame_types', sa.Column('operation', sa.String(length=255), nullable=True))
    op.add_column('aperture_frame_types', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('aperture_frame_types', sa.Column('mull_type', sa.String(length=255), nullable=True))
    op.add_column('aperture_frame_types', sa.Column('source', sa.String(), nullable=True))
    op.add_column('aperture_frame_types', sa.Column('datasheet_url', sa.String(), nullable=True))
    op.add_column('aperture_frame_types', sa.Column('link', sa.String(), nullable=True))
    op.add_column('aperture_frame_types', sa.Column('comments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aperture_frame_types', 'comments')
    op.drop_column('aperture_frame_types', 'link')
    op.drop_column('aperture_frame_types', 'datasheet_url')
    op.drop_column('aperture_frame_types', 'source')
    op.drop_column('aperture_frame_types', 'mull_type')
    op.drop_column('aperture_frame_types', 'location')
    op.drop_column('aperture_frame_types', 'operation')
    op.drop_column('aperture_frame_types', 'use')
    op.drop_column('aperture_frame_types', 'brand')
    op.drop_column('aperture_frame_types', 'psi_g_w_mk')
    # ### end Alembic commands ###
