"""Add Manufacturer

Revision ID: 6b54b6a4efc8
Revises: 515cec25d286
Create Date: 2025-08-17 14:57:25.136730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b54b6a4efc8'
down_revision: Union[str, None] = '515cec25d286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aperture_frame_types', sa.Column('manufacturer', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aperture_frame_types', 'manufacturer')
    # ### end Alembic commands ###
