"""Assembly Orientation

Revision ID: ac7703c5800f
Revises: c48f9091cc32
Create Date: 2025-06-13 13:56:12.579417

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac7703c5800f"
down_revision: Union[str, None] = "c48f9091cc32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assemblies",
        sa.Column(
            "orientation",
            sa.String(),
            nullable=False,
            server_default="first_layer_outside",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assemblies", "orientation")
    # ### end Alembic commands ###
