"""Add content hash

Revision ID: c48f9091cc32
Revises: c5a162313546
Create Date: 2025-06-12 21:06:54.461994

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c48f9091cc32"
down_revision: Union[str, None] = "c5a162313546"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("material_datasheets", sa.Column("content_hash", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_material_datasheets_content_hash"),
        "material_datasheets",
        ["content_hash"],
        unique=False,
    )
    op.add_column("material_photos", sa.Column("content_hash", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_material_photos_content_hash"),
        "material_photos",
        ["content_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_material_photos_content_hash"), table_name="material_photos")
    op.drop_column("material_photos", "content_hash")
    op.drop_index(op.f("ix_material_datasheets_content_hash"), table_name="material_datasheets")
    op.drop_column("material_datasheets", "content_hash")
    # ### end Alembic commands ###
