"""Update

Revision ID: c5a162313546
Revises: 4e441370722a
Create Date: 2025-06-03 12:23:24.693244

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5a162313546"
down_revision: Union[str, None] = "4e441370722a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assembly_layer_segments",
        "layer_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "assembly_layer_segments",
        "material_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "assembly_layer_segments", "order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "assembly_layers", "order", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "assembly_layers", "assembly_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_index(
        op.f("ix_assembly_layers_id"), "assembly_layers", ["id"], unique=False
    )
    op.alter_column(
        "assembly_materials", "argb_color", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "assembly_materials",
        "conductivity_w_mk",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "assembly_materials",
        "emissivity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "assembly_materials",
        "density_kg_m3",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "assembly_materials",
        "specific_heat_j_kgk",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "assembly_materials",
        "specific_heat_j_kgk",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "assembly_materials",
        "density_kg_m3",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "assembly_materials",
        "emissivity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "assembly_materials",
        "conductivity_w_mk",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "assembly_materials", "argb_color", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(op.f("ix_assembly_layers_id"), table_name="assembly_layers")
    op.alter_column(
        "assembly_layers", "assembly_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "assembly_layers", "order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "assembly_layer_segments", "order", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "assembly_layer_segments",
        "material_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "assembly_layer_segments", "layer_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
