"""Add Aperture

Revision ID: ddb558791da6
Revises: ac7703c5800f
Create Date: 2025-07-02 11:19:35.135058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb558791da6'
down_revision: Union[str, None] = 'ac7703c5800f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apertures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('row_heights_mm', sa.Float(), nullable=False),
    sa.Column('column_widths_mm', sa.Float(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apertures_id'), 'apertures', ['id'], unique=False)
    op.create_table('aperture_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_number', sa.Integer(), nullable=False),
    sa.Column('row_span', sa.Integer(), nullable=False),
    sa.Column('col_span', sa.Integer(), nullable=False),
    sa.Column('aperture_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aperture_id'], ['apertures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aperture_elements_id'), 'aperture_elements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aperture_elements_id'), table_name='aperture_elements')
    op.drop_table('aperture_elements')
    op.drop_index(op.f('ix_apertures_id'), table_name='apertures')
    op.drop_table('apertures')
    # ### end Alembic commands ###
