"""add_apertures

Revision ID: fd4af8236c7d
Revises: ac7703c5800f
Create Date: 2025-08-04 11:07:00.321391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4af8236c7d'
down_revision: Union[str, None] = 'ac7703c5800f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aperture_frame_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=False),
    sa.Column('u_value_w_m2k', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aperture_frame_types_id'), 'aperture_frame_types', ['id'], unique=False)
    op.create_table('aperture_glazing_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('u_value_w_m2k', sa.Float(), nullable=False),
    sa.Column('g_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aperture_glazing_types_id'), 'aperture_glazing_types', ['id'], unique=False)
    op.create_table('aperture_element_frame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frame_type_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['frame_type_id'], ['aperture_frame_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aperture_element_frame_id'), 'aperture_element_frame', ['id'], unique=False)
    op.create_table('aperture_element_glazing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('glazing_type_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['glazing_type_id'], ['aperture_glazing_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aperture_element_glazing_id'), 'aperture_element_glazing', ['id'], unique=False)
    op.create_table('apertures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('row_heights_mm', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('column_widths_mm', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apertures_id'), 'apertures', ['id'], unique=False)
    op.create_table('aperture_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('column_number', sa.Integer(), nullable=False),
    sa.Column('row_span', sa.Integer(), nullable=False),
    sa.Column('col_span', sa.Integer(), nullable=False),
    sa.Column('aperture_id', sa.Integer(), nullable=False),
    sa.Column('glazing_id', sa.Integer(), nullable=True),
    sa.Column('frame_top_id', sa.Integer(), nullable=True),
    sa.Column('frame_right_id', sa.Integer(), nullable=True),
    sa.Column('frame_bottom_id', sa.Integer(), nullable=True),
    sa.Column('frame_left_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aperture_id'], ['apertures.id'], ),
    sa.ForeignKeyConstraint(['frame_bottom_id'], ['aperture_element_frame.id'], ),
    sa.ForeignKeyConstraint(['frame_left_id'], ['aperture_element_frame.id'], ),
    sa.ForeignKeyConstraint(['frame_right_id'], ['aperture_element_frame.id'], ),
    sa.ForeignKeyConstraint(['frame_top_id'], ['aperture_element_frame.id'], ),
    sa.ForeignKeyConstraint(['glazing_id'], ['aperture_element_glazing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aperture_elements_id'), 'aperture_elements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aperture_elements_id'), table_name='aperture_elements')
    op.drop_table('aperture_elements')
    op.drop_index(op.f('ix_apertures_id'), table_name='apertures')
    op.drop_table('apertures')
    op.drop_index(op.f('ix_aperture_element_glazing_id'), table_name='aperture_element_glazing')
    op.drop_table('aperture_element_glazing')
    op.drop_index(op.f('ix_aperture_element_frame_id'), table_name='aperture_element_frame')
    op.drop_table('aperture_element_frame')
    op.drop_index(op.f('ix_aperture_glazing_types_id'), table_name='aperture_glazing_types')
    op.drop_table('aperture_glazing_types')
    op.drop_index(op.f('ix_aperture_frame_types_id'), table_name='aperture_frame_types')
    op.drop_table('aperture_frame_types')
    # ### end Alembic commands ###
