import type { ProjectDetail } from "../../projects/types";
import type { ProjectDocumentationSummary } from "../types";

export const PROJECT: ProjectDetail = {
  id: "proj_1",
  name: "Linde Home",
  public_alias: null,
  display_name: "Linde Home",
  bt_number: "2524",
  client: null,
  cert_programs: ["phius"],
  phius_number: null,
  phius_dropbox_url: null,
  active_version_id: "ver_1",
  last_saved_at: null,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-01-01T00:00:00Z",
  versions: [],
  active_version: {
    id: "ver_1",
    project_id: "proj_1",
    name: "Working",
    kind: "working",
    locked: false,
    schema_version: 6,
    body_size_bytes: 1,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
  },
  access_mode: "editor",
  owner_display_name: "Ed May",
};

export function summaryFixture(): ProjectDocumentationSummary {
  return {
    project_id: "proj_1",
    version_id: "ver_1",
    source: "draft",
    version_etag: "v1",
    draft_etag: "d1",
    counts: { spec_done: 2, spec_total: 3, ds_done: 2, ds_total: 3, photo_done: 2, photo_total: 3 },
    sections: [
      {
        key: "equipment",
        title: "Equipment",
        anchor: "equipment",
        counts: {
          spec_done: 2,
          spec_total: 3,
          ds_done: 2,
          ds_total: 3,
          photo_done: 2,
          photo_total: 3,
        },
        records: [],
        groups: [
          {
            key: "ventilators",
            title: "Ventilators",
            anchor: "ventilators",
            counts: {
              spec_done: 1,
              spec_total: 1,
              ds_done: 1,
              ds_total: 1,
              photo_done: 1,
              photo_total: 1,
            },
            records: [
              {
                record_id: "erv_1",
                table_key: "ventilators",
                field_table_key: "ventilators",
                display_name: "Ventilator ERV-01",
                sub_label: "Zehnder · CA350",
                spec_status: "complete",
                datasheet_status: "complete",
                photo_status: "complete",
                datasheet_asset_ids: ["asset_ds_1"],
                photo_asset_ids: ["asset_photo_1"],
                datasheet_not_required: false,
                photo_not_required: false,
                table_path: "/projects/proj_1/equipment?tab=ventilators&focus=erv_1",
                segment_ids: [],
                material_id: null,
              },
            ],
          },
          {
            key: "pumps",
            title: "Pumps",
            anchor: "pumps",
            counts: {
              spec_done: 1,
              spec_total: 2,
              ds_done: 1,
              ds_total: 2,
              photo_done: 1,
              photo_total: 2,
            },
            records: [
              {
                record_id: "pump_1",
                table_key: "pumps",
                field_table_key: "pumps",
                display_name: "Pump P-01",
                sub_label: "Fixture Pump Co · FP-010",
                spec_status: "needed",
                datasheet_status: "needed",
                photo_status: "needed",
                datasheet_asset_ids: [],
                photo_asset_ids: [],
                datasheet_not_required: false,
                photo_not_required: false,
                table_path: "/projects/proj_1/equipment?tab=pumps&focus=pump_1",
                segment_ids: [],
                material_id: null,
              },
              {
                record_id: "pump_2",
                table_key: "pumps",
                field_table_key: "pumps",
                display_name: "Pump P-02",
                sub_label: null,
                spec_status: "na",
                datasheet_status: "na",
                photo_status: "na",
                datasheet_asset_ids: [],
                photo_asset_ids: [],
                datasheet_not_required: true,
                photo_not_required: true,
                table_path: "/projects/proj_1/equipment?tab=pumps&focus=pump_2",
                segment_ids: [],
                material_id: null,
              },
            ],
          },
        ],
      },
    ],
  };
}

export function assetUrlsFixture() {
  return [
    {
      asset_id: "asset_photo_1",
      preview_url: "/preview/photo",
      preview_expires_at: "2026-01-01T00:00:00Z",
      download_url: "/download/photo",
      download_expires_at: "2026-01-01T00:00:00Z",
      thumbnail_url: "/thumb/photo",
      thumbnail_status: "ready",
      thumbnail_expires_at: "2026-01-01T00:00:00Z",
      content_type: "image/jpeg",
      original_filename: "photo.jpg",
      display_name: "photo.jpg",
      size_bytes: 10,
    },
    {
      asset_id: "asset_ds_1",
      preview_url: "/preview/ds",
      preview_expires_at: "2026-01-01T00:00:00Z",
      download_url: "/download/ds",
      download_expires_at: "2026-01-01T00:00:00Z",
      thumbnail_url: null,
      thumbnail_status: "na",
      thumbnail_expires_at: null,
      content_type: "application/pdf",
      original_filename: "datasheet.pdf",
      display_name: "datasheet.pdf",
      size_bytes: 10,
    },
  ];
}

export function pumpsSliceFixture() {
  return {
    project_id: "proj_1",
    version_id: "ver_1",
    source: "draft",
    version_etag: "v1",
    draft_etag: "d1",
    field_defs: [],
    single_select_options: {},
    pumps: [
      {
        id: "pump_1",
        device_type: null,
        phase: null,
        notes: null,
        link: null,
        datasheet_asset_ids: [] as string[],
        datasheet_not_required: false,
        datasheet_status: "needed",
        photo_asset_ids: [] as string[],
        photo_not_required: false,
        photo_status: "needed",
        custom_values: { status: "opt_status_needed" },
      },
      {
        id: "pump_2",
        device_type: null,
        phase: null,
        notes: null,
        link: null,
        datasheet_asset_ids: [] as string[],
        datasheet_not_required: true,
        datasheet_status: "na",
        photo_asset_ids: [] as string[],
        photo_not_required: true,
        photo_status: "na",
        custom_values: { status: "opt_status_na" },
      },
    ],
  };
}
